// Writes dist/_redirects (Cloudflare Pages) so every URL we have ever published keeps working.
// Tour pages moved from /tours/<slug>/ to /bhutan-tours/<category>/<days>-days-<slug>/, so the old
// flat URLs are mapped one by one, read back from what was just built.
import { readdirSync, statSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const DIST = 'dist';
const lines = ['# Generated by scripts/redirects.mjs — do not edit dist/_redirects by hand.'];

// Old flat tour URLs → wherever that tour lives now.
for (const cat of readdirSync(join(DIST, 'bhutan-tours'))) {
  const dir = join(DIST, 'bhutan-tours', cat);
  if (!statSync(dir).isDirectory()) continue;
  for (const tour of readdirSync(dir)) {
    if (!statSync(join(dir, tour)).isDirectory()) continue;
    const old = tour.replace(/^\d+-days-/, '');
    // Both spellings: a placeholder/static rule only matches the exact path it is written as.
    lines.push(`/tours/${old}  /bhutan-tours/${cat}/${tour}/  301`, `/tours/${old}/  /bhutan-tours/${cat}/${tour}/  301`);
  }
}
lines.push(
  '/tours/category/:cat  /bhutan-tours/:cat/  301',
  '/tours/category/:cat/  /bhutan-tours/:cat/  301',
  '/tours  /bhutan-tours/  301',
  '/tours/  /bhutan-tours/  301',
  '/tours/*  /bhutan-tours/  301', // a tour that has since been renamed, moved or retired
);

// Guides that were split or renamed keep their old address working.
const GUIDES = {
  '/travel-guide/best-time-and-weather/': '/travel-guide/best-time-to-visit/',
  '/travel-guide/etiquette-health-and-safety/': '/travel-guide/cultural-etiquette/',
};
for (const [from, to] of Object.entries(GUIDES)) {
  if (existsSync(join(DIST, to.replace(/^\/|\/$/g, ''), 'index.html'))) lines.push(`${from.replace(/\/$/, '')}  ${to}  301`, `${from}  ${to}  301`);
}

const custom = 'public/_redirects';
if (existsSync(custom)) lines.push('', readFileSync(custom, 'utf8').trim());
writeFileSync(join(DIST, '_redirects'), lines.join('\n') + '\n');
console.log(`_redirects: ${lines.length - 1} rules`);
